name: shine_booking_app
description: A haircut booking app similar to 30Shine

environment:
  sdk: ">=3.7.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
    
  provider: ^6.0.0 # Thêm dòng này
  webview_flutter: ^4.7.0 # Sử dụng phiên bản mới nhất

  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  image_picker: ^1.0.4  
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
